import Head from 'next/head';
import { Featured } from '@/components/Featured';
import { PizzaList } from '@/components/PizzaList';
import { Layout } from '@/components/Layout';
import axios from 'axios';
import styles from '@/styles/Home.module.css';


export default function Home({ pizzaList }: { pizzaList: ProductBase[]}) {
  return (
    <Layout>

    <div className={styles.container}>
      <Head>
        <title>Pizzeria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Featured/>      
      <PizzaList pizzaList={pizzaList}/>
     
    </div>
    </Layout>
  )
}





export async function getServerSideProps() {

 const resp = await axios.get("http://localhost:3000/api/products");
  // console.log(resp.status, 'server')

  return {
    props: {
      pizzaList: resp.data,
    
    },
  }
 
}