import Head from 'next/head';
import { useState } from 'react';
import { AddProduct } from '@/components/AddProduct';
import { Featured } from '@/components/Featured';
import { PizzaList } from '@/components/PizzaList';
import { AddButton } from '@/components/AddButton';
import axios from 'axios';
import styles from '@/styles/Home.module.css';
import { Layout } from '@/components/Layout';


export default function Home({ pizzaList, admin }: { pizzaList: ProductBase[], admin: boolean}) {
const [close, setClose] = useState(true);

  return (
    <Layout>

    <div className={styles.container}>
      <Head>
        <title>Pizzeria</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Featured/>
      {admin && <AddButton setClose={setClose}/>}
      <PizzaList pizzaList={pizzaList}/>
      {!close && <AddProduct setClose={setClose}/>}
    </div>
    </Layout>
  )
}





export async function getServerSideProps(ctx: Ctx) {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

//if the token is active
  if(myCookie.token === process.env.TOKEN) {
    //admin already log in
    admin = true; 
  }

  const resp = await axios.get("http://localhost:3000/api/products");
  
  // console.log(ctx, 'server')
 
  return {
    props: {
      pizzaList: resp.data,
      admin,
    },
  }
}