import Head from 'next/head';

export function HeadDocument({ title}: { title : string }) {
  return (
    <Head>
      <title>Pizzeria {title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}